basic_config:
  root_path: './'
  data_name: 'dim_pro8_single_all.mat'
  training_size: 0.2
  batch_size: 32
  total_epoch: 400
  print_freq: 1
  save_freq: 1
  fig_freq: 5
  loss_name: 'mse'
  learning_rate: 1.e-3
  weight_decay: 1.e-9
  learning_beta:
    - 0.99
    - 0.99
  learning_milestones:
    - 200
    - 300
    - 400
  learning_gamma: 0.1

FNO_model:
  in_dim: 10
  out_dim: 4
  modes: 12
  width: 32
  depth: 4
  steps: 1
  padding: 2
  activation: 'gelu'
  dropout: 0.0




